apiVersion : apps/v1
kind: Deployment
metadata:
  name: aks-tomcat-demo
spec:
  replicas: 1
  selector:
     matchLabels:
       app: aks-tomcat-demo
  template:
    metadata:
      labels:
        app: aks-tomcat-demo 
    spec:
      containers:
        - name: aks-tomcat-demo 
          image: tomcatcontainerregistry.azurecr.io/aks-tomcat-demo
          ports:
          - containerPort: 8080
