apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-tomcat-demo
spec:
  replicas: 1
  selector:
    matchLables: 
      app: aks-tomcat-demo
  template:
    metadata:
      labels:
        app: aks-tomcat-demo
    spec:
      containers:
        - name: tomcat
          image: tomcatcontainerregistry.azurecr.io/begimzhanakhmatova/aks-tomcat-demo:60
          ports:
          - containerPort: 8080
