apiVersion: v1
kind: Service
metadata:
    name: begimzhanakhmatovaakstomcatdemo
spec:
    type: LoadBalancer
    ports:
    - port: 8080 
    selector:
        app: begimzhanakhmatovaakstomcatdemo
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: begimzhanakhmatovaakstomcatdemo
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          service:
            name: begimzhanakhmatovaakstomcatdemo
            port:
              number: 80
        pathType: Exact
